import type { ClubEvent, WarningFlag } from './domain';
import { EVENT_STATUS_DEFINITIONS, isActiveStatus } from './domain';
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export const eventDateTimeValue=(e:Pick<ClubEvent,'eventDate'|'startTime'>)=>`${e.eventDate}T${e.startTime}:00`;
export const sortByStart=(events:ClubEvent[])=>[...events].sort((a,b)=>eventDateTimeValue(a).localeCompare(eventDateTimeValue(b))||a.title.localeCompare(b.title));
export const getActiveEvents=(events:ClubEvent[])=>events.filter(e=>isActiveStatus(e.status)&&!e.archivedAt);
export const getUpcomingEventDomain=(events:ClubEvent[], today='2026-07-11', days=14)=>sortByStart(getActiveEvents(events).filter(e=>e.eventDate>=today&&e.eventDate<=addDays(today,days)));
export const getEventsThisWeek=(events:ClubEvent[], today='2026-07-11')=>getUpcomingEventDomain(events,today,7);
export const getNeedsPromotionEvents=(events:ClubEvent[])=>getActiveEvents(events).filter(e=>['approved','marketing','on_sale','final_prep'].includes(e.status)&&e.promotionalReadiness!=='ready');
export const getNeedsStaffingEvents=(events:ClubEvent[], today='2026-07-11')=>getActiveEvents(events).filter(e=>e.eventDate<=addDays(today,7)&&e.staffingReadiness!=='ready');
export const getCancelledEvents=(events:ClubEvent[])=>events.filter(e=>e.status==='cancelled');
export function deriveWarningFlags(e:ClubEvent,today='2026-07-11'):WarningFlag[]{const flags=new Set(e.warningFlags??[]); if(e.expectedAttendance>e.capacity) flags.add('over_capacity'); if(['approved','marketing','on_sale','final_prep'].includes(e.status)&&e.promotionalReadiness!=='ready') flags.add('promotion_late'); if(e.eventDate<=addDays(today,7)&&isActiveStatus(e.status)&&e.staffingReadiness!=='ready') flags.add('staffing_gap'); if(e.status==='final_prep'&&(e.warningFlags?.length??0)>0) flags.add('unresolved_ops'); if(e.eventDate<today&&isActiveStatus(e.status)) flags.add('past_due_active'); return [...flags];}
export const getAtRiskEventDomain=(events:ClubEvent[], today='2026-07-11')=>sortByStart(getActiveEvents(events).filter(e=>deriveWarningFlags(e,today).length>0));
export const getPastDuePreparationEvents=(events:ClubEvent[], today='2026-07-11')=>getActiveEvents(events).filter(e=>e.eventDate<today);
export function filterEvents(events:ClubEvent[], params:Record<string,string|undefined>){let out=[...events]; if(params.archived!=='include') out=out.filter(e=>e.status!=='archived'); if(params.q){const q=params.q.toLowerCase(); out=out.filter(e=>[e.title,e.category,e.venueArea].some(v=>v.toLowerCase().includes(q)));} if(params.status) out=out.filter(e=>e.status===params.status); if(params.risk==='promotion') out=getNeedsPromotionEvents(out); if(params.risk==='staffing') out=getNeedsStaffingEvents(out); if(params.risk==='at_risk') out=getAtRiskEventDomain(out); switch(params.sort){case 'newest': out=sortByStart(out).reverse(); break; case 'updated': out.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)); break; case 'status': out.sort((a,b)=>EVENT_STATUS_DEFINITIONS[a.status].sortOrder-EVENT_STATUS_DEFINITIONS[b.status].sortOrder); break; case 'attendance': out.sort((a,b)=>b.expectedAttendance-a.expectedAttendance); break; default: out=sortByStart(out);} return out;}
export function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`); d.setUTCDate(d.getUTCDate()+days); return d.toISOString().slice(0,10)}
