import { z } from 'zod';
import { VENUE_TIME_ZONE } from './domain';
const time=/^([01]\d|2[0-3]):[0-5]\d$/; const date=/^\d{4}-\d{2}-\d{2}$/;
export const eventFormSchema=z.object({
 title:z.string().trim().min(1,'Title is required').max(90), shortDescription:z.string().trim().min(1,'Short description is required').max(220), internalNotes:z.string().max(1200).optional().or(z.literal('')),
 eventDate:z.string().regex(date,'Use YYYY-MM-DD'), startTime:z.string().regex(time,'Use HH:MM'), endTime:z.string().regex(time,'Use HH:MM'), doorsOpenTime:z.string().regex(time,'Use HH:MM').optional().or(z.literal('')),
 venueArea:z.enum(['main_room','patio','lounge','full_venue']), category:z.enum(['salsa','bachata','cumbia','live_music','private','community','club_night']), agePolicy:z.enum(['all_ages','eighteen_plus','twenty_one_plus']),
 capacity:z.coerce.number().int().positive('Capacity must be greater than zero'), expectedAttendance:z.coerce.number().int().min(0,'Expected attendance cannot be negative'), coverChargeCents:z.coerce.number().int().min(0,'Cover cannot be negative'), ticketUrl:z.string().url('Enter a valid URL').optional().or(z.literal('')), reservationPolicy:z.string().max(500).optional().or(z.literal('')),
 status:z.enum(['idea','planning','approved','marketing','on_sale','final_prep','live','completed','cancelled','archived']), cancelledReason:z.string().max(300).optional().or(z.literal('')), projectedBudgetCents:z.coerce.number().int().min(0,'Projected budget cannot be negative'), promotionalReadiness:z.enum(['not_started','needs_work','ready']), staffingReadiness:z.enum(['not_started','needs_work','ready']), warningFlags:z.array(z.enum(['promotion_late','staffing_gap','over_capacity','budget_risk','unresolved_ops','past_due_active'])).default([])
}).superRefine((v,ctx)=>{ if(v.startTime===v.endTime) ctx.addIssue({code:'custom',path:['endTime'],message:'End time must differ from start time; cross-midnight events are allowed.'}); if(v.expectedAttendance>v.capacity) ctx.addIssue({code:'custom',path:['expectedAttendance'],message:'Expected attendance is above capacity; this will be flagged as a risk.'}); if(v.status==='cancelled'&&!v.cancelledReason?.trim()) ctx.addIssue({code:'custom',path:['cancelledReason'],message:'Cancellation reason is required.'});});
export type EventFormValues=z.infer<typeof eventFormSchema>;
export const toEventInput=(v:EventFormValues)=>({...v, timezone:VENUE_TIME_ZONE, coverCharge:{cents:v.coverChargeCents,currency:'USD' as const}, projectedBudget:{cents:v.projectedBudgetCents,currency:'USD' as const}, ticketUrl:v.ticketUrl||undefined, doorsOpenTime:v.doorsOpenTime||undefined, internalNotes:v.internalNotes||undefined, reservationPolicy:v.reservationPolicy||undefined, cancelledReason:v.cancelledReason||undefined});
