'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { ClubEvent } from '@/lib/admin/events/domain';
import { monthDays, weekDays, groupEventsByLocalDate, nextMonth, prevMonth } from '@/lib/admin/events/calendar';
import { filterEvents } from '@/lib/admin/events/selectors';
import { StatusPill } from './EventUI';
export function CalendarClient({events}:{events:ClubEvent[]}){const [view,setView]=useState<'month'|'week'|'agenda'>('month'); const [anchor,setAnchor]=useState('2026-07-11'); const active=useMemo(()=>filterEvents(events,{archived:'exclude'}),[events]); const grouped=groupEventsByLocalDate(active); const days=view==='week'?weekDays(anchor):monthDays(anchor); return <div className="space-y-5"><div className="flex flex-wrap gap-2 rounded-3xl border border-white/10 bg-black/45 p-4"><button className="rounded-2xl bg-white/10 px-4 py-3" onClick={()=>setAnchor(prevMonth(anchor))}>Previous</button><button className="rounded-2xl bg-amber-300 px-4 py-3 font-bold text-black" onClick={()=>setAnchor('2026-07-11')}>Today</button><button className="rounded-2xl bg-white/10 px-4 py-3" onClick={()=>setAnchor(nextMonth(anchor))}>Next</button>{(['month','week','agenda'] as const).map(v=><button key={v} className={`rounded-2xl px-4 py-3 ${view===v?'bg-red-600':'bg-white/10'}`} onClick={()=>setView(v)}>{v}</button>)}</div>{view==='agenda'?<Agenda grouped={grouped}/>:<div className={`grid gap-2 ${view==='month'?'grid-cols-1 min-[690px]:grid-cols-7':'grid-cols-1 min-[690px]:grid-cols-7'}`}>{days.map(day=><section key={day} className={`min-h-32 rounded-3xl border p-3 ${day==='2026-07-11'?'border-amber-200/50 bg-amber-300/10':'border-white/10 bg-black/35'}`}><h2 className="text-sm font-bold text-amber-100">{day}</h2><div className="mt-2 space-y-2">{(grouped[day]??[]).slice(0,3).map(e=><Link key={e.id} href={`/admin/events/${e.id}`} className={`block rounded-2xl p-2 text-sm ${e.status==='cancelled'?'bg-zinc-500/20 line-through':'bg-red-500/15'}`}><span className="font-medium">{e.startTime} {e.title}</span></Link>)}{(grouped[day]?.length??0)>3&&<p className="text-xs text-white/55">+{(grouped[day]?.length??0)-3} more</p>}</div></section>)}</div>}</div>}
function Agenda({grouped}:{grouped:Record<string,ClubEvent[]>}){const days=Object.keys(grouped).sort(); return <div className="space-y-3">{days.length===0?<p className="rounded-3xl border border-white/10 p-5">No scheduled events.</p>:days.map(day=><section key={day} className="rounded-3xl border border-white/10 bg-black/45 p-4"><h2 className="font-serif text-2xl">{day}</h2><div className="mt-3 space-y-2">{grouped[day].map(e=><Link key={e.id} href={`/admin/events/${e.id}`} className="flex flex-col gap-2 rounded-2xl bg-white/10 p-3 min-[690px]:flex-row min-[690px]:items-center min-[690px]:justify-between"><span>{e.startTime}–{e.endTime} · {e.title}</span><StatusPill status={e.status}/></Link>)}</div></section>)}</div>}
